#ifndef _DEFS_H_
#define _DEFS_H_

#define MAX_LEDS 300

#define DEFAULT_SSID "outofrange"
#define DEFAULT_WIFI_PASSWORD "12345678"
#define DEFAULT_NAME "esp-lights"

#define DEFAULT_WEB_PASSWORD "12345678"

#define DEFAULT_SPEED 100
#define DEFAULT_LOOP_DELAY 100
#define DEFAULT_BRIGHTNESS 32
#define DEFAULT_DENSITY -50

#define DEFAULT_NUM_STRINGS 1
#define DEFAULT_MIRRORED_STRINGS 1


#define DATA_PIN1 32
#define DATA_PIN2 33
#define DATA_PIN3 25
#define DATA_PIN4 26
#endif